# netlify.toml

[build]
  command = "npm run build"
  publish = "build"

# Configuración principal para Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 30 # <-- ¡Aquí! Como una propiedad directa de [functions]
  external_node_modules = ["@google/generative-ai", "stripe"] # <-- ¡Aquí! Como una propiedad directa de [functions]

[build.environment]
  NODE_VERSION = "18"

# Redirigir rutas API a funciones serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200