# netlify.toml

[build]
  command = "npm run build"
  publish = "build"

# Configuración principal para Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Sigo la "Valid syntax" de Netlify: [functions.timeout] es una subsección.
  # Y dentro de ella, ponemos el 'timeout' como una propiedad simple, y las dependencias.
  [functions.timeout]
    timeout = 30 # <-- ¡Definimos el timeout aquí, dentro de la subsección!
    external_node_modules = ["@google/generative-ai", "stripe"]

[build.environment]
  NODE_VERSION = "18"

# Redirigir rutas API a funciones serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200