[build]
  command   = "npm run build"
  publish   = "dist"          # usa "build" si CRA
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[build.environment]
  NODE_VERSION = "20"
