[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]


[build.environment]
  NODE_VERSION = "18"

# Redirigir rutas API a funciones serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
