# netlify.toml

[build]
  command = "npm run build"
  publish = "build"

# Configuración específica para Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Aquí es donde van las propiedades directas del bloque [functions]
  timeout = 30 # <-- ¡CORREGIDO! El timeout va directamente aquí.
  external_node_modules = ["@google/generative-ai", "stripe"] # <-- ¡CORREGIDO! También va directamente aquí.


[build.environment]
  NODE_VERSION = "18"

# Redirigir rutas API a funciones serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200