[build]
  command   = "npm run build"
  publish   = "build"                 # <- aquí el cambio
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[build.environment]
  NODE_VERSION = "20"

# (opcional) redirige /api/* a funciones
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
